#!/usr/bin/env python3
"""Deterministic HTML renderer for the Snapshot Keeper archive.

Reads archive/*.md (human-facing notes produced by the skill) and regenerates,
without any creative writing:

    <root>/index.html                 browsing entry point (search + cards)
    <root>/archive_html/<name>.html   one rendered page per note
    <root>/README.md                  the "## 현재 보관 항목" section only

The skill writes Markdown. HTML is never hand-written: it is regenerated by this
script so the presentation layer stays deterministic and reproducible.

Pure standard library. No third-party dependencies.

Usage:
    python render_archive_html.py
    python render_archive_html.py --archive-root "D:\\_my_tools\\ChatGPT_Snapshot_Archive"
    python render_archive_html.py --no-readme        # skip README rewrite
"""

from __future__ import annotations

import argparse
import html
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

DEFAULT_ROOT = r"D:\_my_tools\ChatGPT_Snapshot_Archive"
README_SECTION = "## 현재 보관 항목"
CHATGPT_LINK_RE = re.compile(r"원본 대화:\s*\[[^\]]*\]\((https?://[^)]+)\)")
CONV_KEY_RE = re.compile(r"chatgpt:c-([0-9a-fA-F-]+)")
FOLDER_ID_RE = re.compile(r"__c-([0-9a-fA-F-]+)")
FILENAME_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})_(turn[0-9]+(?:-[0-9]+)?)_")
STATUS_WORDS = ("saved", "missing", "variant", "escape", "invalid")
PROJECT_MONTH_RE = re.compile(r"^\d{4}-\d{2}$")


# --------------------------------------------------------------------------- #
# Note model
# --------------------------------------------------------------------------- #
@dataclass
class Note:
    path: Path
    name: str                       # filename stem
    md_filename: str                # original *.md filename
    html_filename: str              # <stem>.html
    title: str
    date: str
    turn_range: str
    chatgpt_url: Optional[str]
    summary: str
    keywords: List[str]
    status_counts: Dict[str, int]
    body_md: str                    # markdown after the title line / 원본 대화 line
    raw: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig", errors="replace")


def strip_frontmatter(text: str) -> str:
    text = text.lstrip("﻿")
    if text.startswith("---"):
        m = re.match(r"^---\s*\n.*?\n---\s*\n?", text, flags=re.S)
        if m:
            return text[m.end():]
    return text


def parse_note(path: Path) -> Note:
    raw = read_text(path)
    body = strip_frontmatter(raw)
    lines = body.splitlines()

    # title = first H1
    title = path.stem
    title_idx = -1
    for i, line in enumerate(lines):
        if line.startswith("# "):
            title = line[2:].strip()
            title_idx = i
            break

    # chatgpt url: explicit "원본 대화" link, else reconstruct from conv key / folder
    url_match = CHATGPT_LINK_RE.search(body)
    chatgpt_url = url_match.group(1) if url_match else None
    if not chatgpt_url:
        m = CONV_KEY_RE.search(body) or FOLDER_ID_RE.search(body)
        if m:
            chatgpt_url = f"https://chatgpt.com/c/{m.group(1)}"

    summary = extract_section_text(lines, "선요약")
    kw_text = extract_section_text(lines, "검색 키워드")
    keywords = [k.strip() for k in re.split(r"[,\n]", kw_text) if k.strip()] if kw_text else []

    status_counts = parse_status_counts(body)
    date, turn_range = parse_filename_meta(path.name)
    if not turn_range:
        turn_range = guess_turn_range(body)

    # body for the detail page: drop the leading title line and the 원본 대화 line
    drop = set()
    if title_idx >= 0:
        drop.add(title_idx)
    for i, line in enumerate(lines):
        if line.strip().startswith("원본 대화:"):
            drop.add(i)
    body_md = "\n".join(l for i, l in enumerate(lines) if i not in drop).strip()

    return Note(
        path=path,
        name=path.stem,
        md_filename=path.name,
        html_filename=path.stem + ".html",
        title=title,
        date=date,
        turn_range=turn_range,
        chatgpt_url=chatgpt_url,
        summary=summary,
        keywords=keywords,
        status_counts=status_counts,
        body_md=body_md,
        raw=raw,
    )


def extract_section_text(lines: List[str], heading: str) -> str:
    """Return the text content directly under '## <heading>' until the next '## '."""
    out: List[str] = []
    collecting = False
    for line in lines:
        if re.match(r"^##\s+", line):
            if collecting:
                break
            collecting = re.sub(r"^##\s+", "", line).strip() == heading
            continue
        if collecting:
            out.append(line)
    return "\n".join(out).strip()


def parse_status_counts(body: str) -> Dict[str, int]:
    """Prefer an explicit 'status counts: saved n / missing n' line; else count the 파일 범위 table."""
    counts = {w: 0 for w in STATUS_WORDS}
    m = re.search(r"status counts:\s*(.+)", body)
    if m:
        for word in STATUS_WORDS:
            wm = re.search(rf"{word}\s+(\d+)", m.group(1))
            if wm:
                counts[word] = int(wm.group(1))
        if any(counts.values()):
            return {k: v for k, v in counts.items() if v}
    # fallback: count status column of the 파일 범위 table
    for line in body.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) >= 2:
            status = cells[1].lower()
            if status in counts:
                counts[status] += 1
    return {k: v for k, v in counts.items() if v}


def parse_filename_meta(filename: str) -> Tuple[str, str]:
    m = FILENAME_RE.match(filename)
    if m:
        return m.group(1), m.group(2)
    return "", ""


def guess_turn_range(body: str) -> str:
    m = re.search(r"turn range:\s*(turn[0-9-]+)", body)
    return m.group(1) if m else ""


# --------------------------------------------------------------------------- #
# Source snapshots (snapshots/**/*.md) -> snapshot_html drill-down pages
# --------------------------------------------------------------------------- #
@dataclass
class SnapshotDoc:
    path: Path
    rel: str            # path relative to snapshots/ (forward slashes, .md)
    html_rel: str       # same path with .html
    turn: Optional[int]
    status: str
    detected_at: str
    reason: str
    missing_sections: List[str]
    conv_url: Optional[str]
    conv_id: Optional[str]
    body_md: str


def conv_id_from(value: str) -> Optional[str]:
    s = str(value or "")
    m = re.search(r"/c/([0-9a-fA-F-]+)", s) or re.search(r"c-([0-9a-fA-F-]+)", s)
    return m.group(1) if m else None


def parse_frontmatter_map(text: str) -> Dict[str, object]:
    text = text.lstrip("﻿")
    if not text.startswith("---"):
        return {}
    m = re.match(r"^---\s*\n(.*?)\n---", text, flags=re.S)
    if not m:
        return {}
    meta: Dict[str, object] = {}
    current: Optional[str] = None
    for line in m.group(1).splitlines():
        kv = re.match(r"^([A-Za-z_][\w]*):\s*(.*)$", line)
        if kv:
            current = kv.group(1)
            meta[current] = kv.group(2).strip().strip('"').strip("'")
        elif current and line.strip().startswith("-"):
            meta.setdefault(current + "__list", []).append(
                line.strip()[1:].strip().strip('"').strip("'")
            )
    return meta


def parse_snapshot(path: Path, snapshots_dir: Path) -> SnapshotDoc:
    raw = read_text(path)
    meta = parse_frontmatter_map(raw)
    body = strip_frontmatter(raw)
    rel = path.relative_to(snapshots_dir).as_posix()
    html_rel = (rel[:-3] if rel.lower().endswith(".md") else rel) + ".html"

    turn: Optional[int] = None
    turn_meta = str(meta.get("turn") or "")
    if re.search(r"\d+", turn_meta):
        turn = int(re.search(r"\d+", turn_meta).group())
    else:
        fm = re.search(r"turn[_-]?(\d+)", path.name, flags=re.I)
        if fm:
            turn = int(fm.group(1))

    conv_url = str(meta.get("conversationUrl") or "") or None
    conv_id = conv_id_from(str(meta.get("conversationKey") or "") or conv_url or rel)
    if not conv_url and conv_id:
        conv_url = f"https://chatgpt.com/c/{conv_id}"

    return SnapshotDoc(
        path=path,
        rel=rel,
        html_rel=html_rel,
        turn=turn,
        status=str(meta.get("status") or "unknown").lower(),
        detected_at=str(meta.get("detectedAt") or ""),
        reason=str(meta.get("reason") or ""),
        missing_sections=list(meta.get("missingSections__list") or []),
        conv_url=conv_url,
        conv_id=conv_id,
        body_md=body.strip(),
    )


def arch_to_snap_href(html_rel: str) -> str:
    """Relative href from an archive_html/<note>.html page to a snapshot page."""
    return "../snapshot_html/" + html_rel


def inject_snapshot_links(body_md: str, turn_href: Dict[int, str], path_href: Dict[str, str]) -> str:
    """Add a '원문 보기' link in the 메모 cell of 파일 범위 rows and on 원문 근거 파일 paths."""
    out: List[str] = []
    for line in body_md.splitlines():
        new = line
        if line.lstrip().startswith("|"):
            cells = line.split("|")
            turn_txt = cells[1].strip() if len(cells) >= 6 else ""
            if turn_txt.isdigit() and int(turn_txt) in turn_href:
                href = turn_href[int(turn_txt)]
                memo = cells[-2].strip()
                cells[-2] = f" {memo + ' · ' if memo else ''}[원문 보기]({href}) "
                out.append("|".join(cells))
                continue
        pm = re.match(r"^(\s*[-*]\s*)`?(snapshots/[^\s`]+?\.md)`?\s*$", line)
        if pm and pm.group(2) in path_href:
            base = pm.group(2).split("/")[-1]
            new = f"{pm.group(1)}[{base} 열기]({path_href[pm.group(2)]})"
        out.append(new)
    return "\n".join(out)


def render_snapshot_page(snap: SnapshotDoc, note: "Optional[Note]") -> str:
    ups = "../" * len(snap.html_rel.split("/"))
    btns: List[str] = []
    if note is not None:
        btns.append(
            f'<a class="btn" href="{ups}archive_html/'
            f'{html.escape(note.html_filename, quote=True)}">{ARROW_LEFT} 노트</a>'
        )
    btns.append(f'<a class="btn" href="{ups}index.html">{ARROW_LEFT} 인덱스</a>')
    conv_btn = (
        f'<a class="btn btn-accent" href="{html.escape(snap.conv_url, quote=True)}" '
        f'target="_blank" rel="noopener">원본 ChatGPT 대화 열기 {ARROW_UR}</a>'
        if snap.conv_url else '<span class="btn" style="opacity:.5">원본 링크 없음</span>'
    )
    topbar = (
        '<div class="topbar"><div class="inner">'
        + "".join(btns)
        + '<span class="spacer"></span>'
        + conv_btn
        + "</div></div>"
    )
    st = snap.status if snap.status in STATUS_WORDS else "saved"
    meta_bits = [f'<span class="st {st}">{html.escape(snap.status)}</span>']
    if snap.turn is not None:
        meta_bits.append(f'<span class="pill">turn {snap.turn}</span>')
    if snap.detected_at:
        meta_bits.append(f'<span class="pill">{html.escape(snap.detected_at)}</span>')
    if snap.reason:
        meta_bits.append(f'<span class="pill">{html.escape(snap.reason)}</span>')
    title = f"turn {snap.turn} · {snap.status}" if snap.turn is not None else snap.status
    miss = ""
    if snap.missing_sections:
        items = "".join(f"<li>{html.escape(s)}</li>" for s in snap.missing_sections)
        miss = f'<p style="color:var(--muted);margin:.6em 0 .2em">누락 섹션</p><ul>{items}</ul>'
    body = (
        f'<div class="note"><h1>{html.escape(title)}</h1>'
        f'<div class="convbar">{"".join(meta_bits)}</div>'
        f"{miss}{render_markdown(snap.body_md)}</div>"
    )
    return page_shell(title, topbar, body)


# --------------------------------------------------------------------------- #
# Minimal, safe Markdown -> HTML (covers what the notes actually use)
# --------------------------------------------------------------------------- #
def render_inline(text: str) -> str:
    """Escape, then apply inline markdown: code, links, bold, italic, bare urls."""
    placeholders: List[str] = []
    sent_l, sent_r = "@@PH", "HP@@"

    def stash(rendered: str) -> str:
        placeholders.append(rendered)
        return f"{sent_l}{len(placeholders) - 1}{sent_r}"

    # inline code first (its contents must not be further processed)
    def code_sub(m: re.Match) -> str:
        return stash(f"<code>{html.escape(m.group(1))}</code>")

    text = re.sub(r"`([^`]+)`", code_sub, text)

    # markdown links [text](url): external opens a new tab, internal stays in the same tab
    def link_sub(m: re.Match) -> str:
        label = html.escape(m.group(1))
        url = m.group(2).strip()
        if re.match(r"^(https?:|mailto:)", url):
            return stash(
                f'<a href="{html.escape(url, quote=True)}" target="_blank" rel="noopener">{label}</a>'
            )
        safe = url if re.match(r"^(/|\.|#)", url) else "#"
        return stash(f'<a href="{html.escape(safe, quote=True)}">{label}</a>')

    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", link_sub, text)

    # escape everything still raw
    text = html.escape(text)

    # bold / italic on escaped text
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", text)

    # autolink bare urls
    def bare(m: re.Match) -> str:
        u = m.group(0)
        return f'<a href="{u}" target="_blank" rel="noopener">{u}</a>'

    text = re.sub(r"(?<![\"'>=])\bhttps?://[^\s<]+", bare, text)

    # restore placeholders
    for i, rendered in enumerate(placeholders):
        text = text.replace(f"{sent_l}{i}{sent_r}", rendered)
    return text


def render_markdown(md: str) -> str:
    lines = md.splitlines()
    out: List[str] = []
    i = 0
    n = len(lines)

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # heading
        h = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if h:
            level = len(h.group(1))
            out.append(f"<h{level}>{render_inline(h.group(2).strip())}</h{level}>")
            i += 1
            continue

        # table block
        if stripped.startswith("|") and i + 1 < n and re.match(r"^\|[\s:|-]+\|?$", lines[i + 1].strip()):
            tbl, i = render_table(lines, i)
            out.append(tbl)
            continue

        # Fallback for pipe-prefixed lines that are not valid Markdown table
        # headers. Without consuming the line, the paragraph parser below would
        # see a block-start character and loop forever.
        if stripped.startswith("|"):
            out.append(f"<p>{render_inline(stripped)}</p>")
            i += 1
            continue

        # unordered list block
        if re.match(r"^[-*]\s+", stripped):
            items: List[str] = []
            while i < n and re.match(r"^[-*]\s+", lines[i].strip()):
                items.append(render_inline(re.sub(r"^[-*]\s+", "", lines[i].strip())))
                i += 1
            out.append("<ul>" + "".join(f"<li>{it}</li>" for it in items) + "</ul>")
            continue

        # paragraph (gather until blank / block start)
        para: List[str] = []
        while i < n and lines[i].strip() and not re.match(r"^(#{1,6}\s|[-*]\s|\|)", lines[i].strip()):
            para.append(lines[i].strip())
            i += 1
        out.append(f"<p>{render_inline(' '.join(para))}</p>")

    return "\n".join(out)


def render_table(lines: List[str], start: int) -> Tuple[str, int]:
    header = [c.strip() for c in lines[start].strip().strip("|").split("|")]
    i = start + 2
    rows: List[List[str]] = []
    while i < len(lines) and lines[i].strip().startswith("|"):
        rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
        i += 1
    thead = "<tr>" + "".join(f"<th>{render_inline(c)}</th>" for c in header) + "</tr>"
    tbody = "".join(
        "<tr>" + "".join(f"<td>{render_inline(c)}</td>" for c in r) + "</tr>" for r in rows
    )
    return f"<table><thead>{thead}</thead><tbody>{tbody}</tbody></table>", i


# --------------------------------------------------------------------------- #
# Theme (OpenAI-style dark)
# --------------------------------------------------------------------------- #
CSS = """
:root{
  --bg:#0d0d0d; --surface:#171717; --surface-2:#1f1f1f; --border:#2c2c2c;
  --text:#ececec; --muted:#9b9b9b; --accent:#10a37f; --accent-soft:#1a7f64;
    --chip:#262626; --radius:14px; --warn:#d79a2b; --ok:#10a37f;
  --saved:#10a37f; --missing:#e0683b; --variant:#c9a227; --escape:#4f8cff; --invalid:#a64dff;
}
*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{
  margin:0; background:var(--bg); color:var(--text);
  font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Noto Sans KR",sans-serif;
  -webkit-font-smoothing:antialiased;
}
a{color:var(--accent); text-decoration:none}
a:hover{text-decoration:underline}
.wrap{max-width:1040px; margin:0 auto; padding:32px 20px 80px}
.topbar{
  position:sticky; top:0; z-index:10; backdrop-filter:blur(8px);
  background:rgba(13,13,13,.82); border-bottom:1px solid var(--border);
}
.topbar .inner{max-width:1040px; margin:0 auto; padding:12px 20px; display:flex; align-items:center; gap:14px}
.brand{font-weight:700; letter-spacing:.2px; display:flex; align-items:center; gap:9px}
.dot{width:10px;height:10px;border-radius:50%;background:var(--accent);box-shadow:0 0 12px var(--accent)}
.spacer{flex:1}
.btn{
  display:inline-flex; align-items:center; gap:7px; padding:8px 14px; border-radius:999px;
  border:1px solid var(--border); background:var(--surface-2); color:var(--text);
  font-size:13px; font-weight:600; cursor:pointer; transition:.15s;
}
.btn:hover{border-color:var(--accent); text-decoration:none; transform:translateY(-1px)}
.btn-accent{background:var(--accent); border-color:var(--accent); color:#06251c}
.btn-accent:hover{background:#13b88f}
h1.page{font-size:26px; margin:6px 0 4px}
.sub{color:var(--muted); margin:0 0 26px}
.sync-banner{
  display:flex; align-items:center; gap:12px; margin:14px 0 24px; padding:13px 15px;
  border:1px solid var(--border); border-radius:12px; background:var(--surface);
}
.sync-banner .signal{width:10px; height:10px; border-radius:50%; flex:0 0 auto}
.sync-banner .copy{display:flex; flex-direction:column; gap:2px}
.sync-banner .title{font-size:13.5px; font-weight:800; color:var(--text)}
.sync-banner .detail{font-size:12.5px; color:var(--muted)}
.sync-banner.pending{border-color:#65481d; background:#1e1710}
.sync-banner.pending .signal{background:var(--warn); box-shadow:0 0 16px rgba(215,154,43,.45)}
.sync-banner.complete{border-color:#1f4d40; background:#101d19}
.sync-banner.complete .signal{background:var(--ok); box-shadow:0 0 16px rgba(16,163,127,.35)}
.search{
  width:100%; padding:13px 16px; margin:0 0 24px; border-radius:999px;
  border:1px solid var(--border); background:var(--surface); color:var(--text); font-size:15px;
}
.search:focus{outline:none; border-color:var(--accent)}
.grid{display:grid; grid-template-columns:repeat(auto-fill,minmax(320px,1fr)); gap:16px}
.card{
  background:var(--surface); border:1px solid var(--border); border-radius:var(--radius);
  padding:18px; display:flex; flex-direction:column; gap:11px; transition:.15s;
}
.card:hover{border-color:#3a3a3a; transform:translateY(-2px); box-shadow:0 10px 30px rgba(0,0,0,.35)}
.card .meta{display:flex; gap:8px; align-items:center; flex-wrap:wrap; font-size:12px; color:var(--muted)}
.card h2{font-size:17px; margin:0; line-height:1.35}
.card h2 a{color:var(--text)}
.card h2 a:hover{color:var(--accent); text-decoration:none}
.card .summary{color:#c9c9c9; font-size:13.5px; margin:0}
.pill{padding:2px 9px; border-radius:999px; background:var(--chip); border:1px solid var(--border); white-space:nowrap}
.chips{display:flex; flex-wrap:wrap; gap:6px}
.chip{font-size:11.5px; padding:3px 9px; border-radius:999px; background:var(--surface-2); border:1px solid var(--border); color:#bdbdbd}
.statuses{display:flex; gap:6px; flex-wrap:wrap; margin-top:2px}
.st{font-size:11.5px; font-weight:700; padding:2px 9px; border-radius:999px; border:1px solid}
.st.saved{color:var(--saved); border-color:#155e49; background:#0f2a22}
.st.missing{color:var(--missing); border-color:#5e3320; background:#2a1a12}
.st.variant{color:var(--variant); border-color:#5e5320; background:#2a2612}
.st.escape{color:var(--escape); border-color:#27487d; background:#101d35}
.st.invalid{color:var(--invalid); border-color:#4a2a6e; background:#1f1430}
.card .foot{margin-top:auto; display:flex; gap:10px; align-items:center; padding-top:6px}
.card .foot a{font-size:12.5px; font-weight:600}
.copy-delete{
  border:0; background:transparent; color:#e0683b; font-size:12.5px; font-weight:700;
  padding:0; cursor:pointer; margin-left:auto;
}
.copy-delete:hover{text-decoration:underline}
.empty{color:var(--muted); text-align:center; padding:60px 0}
/* detail page */
.note{
  background:var(--surface); border:1px solid var(--border); border-radius:var(--radius);
  padding:30px 32px; margin-top:18px;
}
.note h1{font-size:24px; margin:.2em 0 .5em}
.note h2{font-size:18px; margin:1.6em 0 .5em; padding-bottom:6px; border-bottom:1px solid var(--border); color:#fff}
.note h3{font-size:15px; margin:1.2em 0 .3em; color:var(--accent)}
.note p{margin:.5em 0}
.note ul{margin:.4em 0 .9em; padding-left:1.3em}
.note li{margin:.2em 0}
.note code{background:#0a0a0a; border:1px solid var(--border); border-radius:6px; padding:1px 6px; font-size:.88em; color:#e6c07b}
.note a{word-break:break-all}
.note table{width:100%; border-collapse:collapse; margin:.8em 0; font-size:13.5px}
.note th,.note td{border:1px solid var(--border); padding:7px 10px; text-align:left}
.note thead th{background:var(--surface-2); color:#fff}
.note tbody tr:nth-child(even){background:rgba(255,255,255,.02)}
.note td a{font-weight:600}
.note .convbar{
  display:flex; gap:10px; flex-wrap:wrap; align-items:center;
  background:var(--surface-2); border:1px solid var(--border); border-radius:12px;
  padding:12px 16px; margin-bottom:4px;
}
.note .convbar .lbl{color:var(--muted); font-size:13px}
.footer{margin-top:40px; color:var(--muted); font-size:12px; text-align:center}
"""

ARROW_LEFT = "&#8592;"
ARROW_UR = "&#8599;"


def page_shell(title: str, topbar_html: str, body_html: str, css_href: Optional[str] = None) -> str:
    style = f'<link rel="stylesheet" href="{css_href}">' if css_href else f"<style>{CSS}</style>"
    return f"""<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
{style}
</head>
<body>
{topbar_html}
<div class="wrap">
{body_html}
<div class="footer">conversation-snapshot-indexer · render_archive_html.py 로 자동 생성됨 · 직접 편집하지 마세요</div>
</div>
</body>
</html>
"""


def render_index(notes: List[Note], pending_project_jobs: int, generated_iso: str, generated_label: str) -> str:
    topbar = (
        '<div class="topbar"><div class="inner">'
        '<span class="brand"><span class="dot"></span>ChatGPT Snapshot Archive</span>'
        '<span class="spacer"></span>'
        f'<span class="pill">{len(notes)} notes</span>'
        "</div></div>"
    )
    cards: List[str] = []
    for note in notes:
        chips = "".join(f'<span class="chip">{html.escape(k)}</span>' for k in note.keywords[:8])
        statuses = "".join(
            f'<span class="st {s}">{s} {note.status_counts[s]}</span>'
            for s in STATUS_WORDS if note.status_counts.get(s)
        )
        meta_bits = []
        if note.date:
            meta_bits.append(f'<span class="pill">{html.escape(note.date)}</span>')
        if note.turn_range:
            meta_bits.append(f'<span class="pill">{html.escape(note.turn_range)}</span>')
        conv = (
            f'<a href="{html.escape(note.chatgpt_url, quote=True)}" target="_blank" rel="noopener">'
            f"&#8599; 원본 대화</a>"
            if note.chatgpt_url else ""
        )
        delete_cmd = (
            'python "D:\\_my_tools\\ChatGPT_Snapshot\\skills\\conversation-snapshot-indexer\\scripts\\delete_archive_item.py" '
            '--archive-root "D:\\_my_tools\\ChatGPT_Snapshot_Archive" '
            '--project-root "D:\\_my_tools\\ChatGPT_Snapshot" '
            f'--note "{note.md_filename}" --confirm'
        )
        search_blob = html.escape(
            " ".join([note.title, note.summary, " ".join(note.keywords), note.date, note.turn_range])
        ).lower()
        cards.append(
            f'''<article class="card" data-search="{search_blob}">
  <div class="meta">{''.join(meta_bits)}</div>
  <h2><a href="archive_html/{html.escape(note.html_filename, quote=True)}">{html.escape(note.title)}</a></h2>
  <p class="summary">{html.escape(note.summary or '선요약 없음 · 원문 확인 필요')}</p>
  <div class="chips">{chips}</div>
  <div class="statuses">{statuses}</div>
  <div class="foot"><a href="archive_html/{html.escape(note.html_filename, quote=True)}">열기 →</a>{conv}<button class="copy-delete" type="button" data-delete-cmd="{html.escape(delete_cmd, quote=True)}">삭제</button></div>
</article>'''
        )

    if pending_project_jobs:
        sync_class = "pending"
        sync_title = f"Archive Sync 대기 {pending_project_jobs}개 존재"
        sync_detail = f"{generated_label} 기준 상태입니다."
    else:
        sync_class = "complete"
        sync_title = "Archive Sync 완료"
        sync_detail = f"{generated_label} 기준 상태입니다."

    body = f"""<h1 class="page">보관된 대화 아카이브</h1>
<div class="sync-banner {sync_class}" data-generated-at="{html.escape(generated_iso, quote=True)}">
  <span class="signal"></span>
  <span class="copy">
    <span class="title" data-sync-title="{html.escape(sync_title, quote=True)}">{html.escape(sync_title)}</span>
    <span class="detail" data-sync-detail="{html.escape(sync_detail, quote=True)}">{html.escape(sync_detail)}</span>
  </span>
</div>
<input id="q" class="search" type="search" placeholder="제목 · 선요약 · 키워드 검색…" autocomplete="off">
<div class="grid" id="grid">
{''.join(cards)}
</div>
<div class="empty" id="empty" style="display:none">검색 결과가 없습니다.</div>
<script>
const q=document.getElementById('q'),cards=[...document.querySelectorAll('.card')],empty=document.getElementById('empty');
const syncBanner=document.querySelector('.sync-banner');
if(syncBanner){{
  const generatedAt=new Date(syncBanner.dataset.generatedAt);
  const title=syncBanner.querySelector('[data-sync-title]');
  const detail=syncBanner.querySelector('[data-sync-detail]');
  if(!Number.isNaN(generatedAt.getTime())&&title&&detail){{
    const dayMs=24*60*60*1000;
    const today=new Date(); today.setHours(0,0,0,0);
    const generatedDay=new Date(generatedAt); generatedDay.setHours(0,0,0,0);
    const elapsedDays=Math.max(0,Math.floor((today-generatedDay)/dayMs));
    title.textContent=`${{title.dataset.syncTitle}} · 마지막 갱신 +${{elapsedDays}}일 경과`;
    detail.textContent=elapsedDays>=2
      ? `${{detail.dataset.syncDetail}} 문서 갱신하세요.`
      : detail.dataset.syncDetail;
  }}
}}
q.addEventListener('input',()=>{{
  const t=q.value.trim().toLowerCase();let shown=0;
  cards.forEach(c=>{{const hit=!t||c.dataset.search.includes(t);c.style.display=hit?'':'none';if(hit)shown++;}});
  empty.style.display=shown?'none':'block';
}});
document.addEventListener('click',async(e)=>{{
  const b=e.target.closest('[data-delete-cmd]');
  if(!b)return;
  const cmd=b.dataset.deleteCmd;
  try{{await navigator.clipboard.writeText(cmd);b.textContent='복사됨';}}
  catch(_){{
    const ta=document.createElement('textarea');ta.value=cmd;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();b.textContent='복사됨';
  }}
  setTimeout(()=>b.textContent='삭제',1400);
}});
</script>"""
    return page_shell("ChatGPT Snapshot Archive", topbar, body)


def project_root_from_script() -> Path:
    """The skill lives under <project>/skills/...; project-root jobs must not be hidden in the archive root."""
    return Path(__file__).resolve().parents[3]


def count_project_snapshot_jobs(project_root: Path) -> int:
    total = 0
    for month_dir in project_root.iterdir():
        if not month_dir.is_dir() or not PROJECT_MONTH_RE.match(month_dir.name):
            continue
        total += sum(1 for child in month_dir.iterdir() if child.is_dir())
    return total


def render_detail(note: Note, turn_href: Optional[Dict[int, str]] = None,
                  path_href: Optional[Dict[str, str]] = None) -> str:
    conv_btn = (
        f'<a class="btn btn-accent" href="{html.escape(note.chatgpt_url, quote=True)}" '
        f'target="_blank" rel="noopener">원본 ChatGPT 대화 열기 {ARROW_UR}</a>'
        if note.chatgpt_url else '<span class="btn" style="opacity:.5">원본 링크 없음</span>'
    )
    topbar = (
        '<div class="topbar"><div class="inner">'
        f'<a class="btn" href="../index.html">{ARROW_LEFT} 인덱스</a>'
        '<span class="spacer"></span>'
        f"{conv_btn}"
        "</div></div>"
    )
    convbar = ""
    if note.chatgpt_url:
        convbar = (
            '<div class="convbar"><span class="lbl">원본 대화</span>'
            f'<a href="{html.escape(note.chatgpt_url, quote=True)}" target="_blank" rel="noopener">'
            f"{html.escape(note.chatgpt_url)}</a></div>"
        )
    body_md = inject_snapshot_links(note.body_md, turn_href or {}, path_href or {})
    body = f'<div class="note"><h1>{html.escape(note.title)}</h1>{convbar}{render_markdown(body_md)}</div>'
    return page_shell(note.title, topbar, body)


# --------------------------------------------------------------------------- #
# README "현재 보관 항목" section
# --------------------------------------------------------------------------- #
def build_readme_section(notes: List[Note]) -> str:
    lines = [README_SECTION, "", "- 빠른 탐색: [index.html](index.html)", ""]
    for note in notes:
        lines.append(f"- [{note.md_filename}](archive/{note.md_filename})")
    return "\n".join(lines) + "\n"


def update_readme(readme_path: Path, notes: List[Note]) -> bool:
    if not readme_path.exists():
        return False
    raw = readme_path.read_bytes()
    has_bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig", errors="replace")
    section = build_readme_section(notes)

    if README_SECTION in text:
        pattern = re.compile(
            re.escape(README_SECTION) + r".*?(?=\n## |\Z)", flags=re.S
        )
        new_text = pattern.sub(section.rstrip("\n") + "\n", text, count=1)
    else:
        new_text = text.rstrip("\n") + "\n\n" + section

    if new_text == text:
        return False
    data = new_text.encode("utf-8")
    if has_bom:
        data = b"\xef\xbb\xbf" + data
    readme_path.write_bytes(data)
    return True


# --------------------------------------------------------------------------- #
def main() -> None:
    ap = argparse.ArgumentParser(description="Render the snapshot archive to HTML (deterministic).")
    ap.add_argument("--archive-root", default=DEFAULT_ROOT, help="archive root containing archive/*.md")
    ap.add_argument("--no-readme", action="store_true", help="do not rewrite README.md")
    args = ap.parse_args()

    root = Path(args.archive_root).expanduser()
    archive_dir = root / "archive"
    if not archive_dir.is_dir():
        raise SystemExit(f"archive folder not found: {archive_dir}")

    md_files = sorted(p for p in archive_dir.glob("*.md") if p.name.lower() != "readme.md")
    if not md_files:
        raise SystemExit(f"no archive notes found in {archive_dir}")

    notes = [parse_note(p) for p in md_files]
    # newest first by date, then filename — stable & deterministic
    notes.sort(key=lambda n: (n.date, n.name), reverse=True)

    html_dir = root / "archive_html"
    html_dir.mkdir(exist_ok=True)

    # clean stale html for removed notes
    valid_html = {n.html_filename for n in notes}
    for stale in html_dir.glob("*.html"):
        if stale.name not in valid_html:
            stale.unlink()

    # source snapshots -> snapshot_html drill-down pages
    snapshots_dir = root / "snapshots"
    snaps: List[SnapshotDoc] = []
    if snapshots_dir.is_dir():
        snaps = [parse_snapshot(p, snapshots_dir) for p in sorted(snapshots_dir.rglob("*.md"))]

    note_by_conv: Dict[str, Note] = {}
    for note in notes:
        cid = conv_id_from(note.chatgpt_url or "")
        if cid and cid not in note_by_conv:
            note_by_conv[cid] = note

    snap_dir = root / "snapshot_html"
    if snaps:
        snap_dir.mkdir(exist_ok=True)
        valid_snaps = {s.html_rel for s in snaps}
        for stale in snap_dir.rglob("*.html"):
            if stale.relative_to(snap_dir).as_posix() not in valid_snaps:
                stale.unlink()
        for snap in snaps:
            target = snap_dir / snap.html_rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(
                render_snapshot_page(snap, note_by_conv.get(snap.conv_id)), encoding="utf-8"
            )

    # per-note maps: turn -> snapshot page, "snapshots/<rel>" -> snapshot page
    snaps_by_conv: Dict[str, List[SnapshotDoc]] = {}
    for snap in snaps:
        if snap.conv_id:
            snaps_by_conv.setdefault(snap.conv_id, []).append(snap)

    for note in notes:
        cid = conv_id_from(note.chatgpt_url or "")
        group = snaps_by_conv.get(cid or "", [])
        turn_href = {s.turn: arch_to_snap_href(s.html_rel) for s in group if s.turn is not None}
        path_href = {"snapshots/" + s.rel: arch_to_snap_href(s.html_rel) for s in group}
        (html_dir / note.html_filename).write_text(
            render_detail(note, turn_href, path_href), encoding="utf-8"
        )

    pending_project_jobs = count_project_snapshot_jobs(project_root_from_script())
    generated_at = datetime.now().astimezone()
    generated_iso = generated_at.isoformat(timespec="minutes")
    generated_label = generated_at.strftime("%Y.%m.%d")
    (root / "index.html").write_text(
        render_index(notes, pending_project_jobs, generated_iso, generated_label),
        encoding="utf-8",
    )

    readme_changed = False
    if not args.no_readme:
        readme_changed = update_readme(root / "README.md", notes)

    print(f"notes rendered : {len(notes)}")
    print(f"index.html     : {root / 'index.html'}")
    print(f"archive_html/  : {html_dir} ({len(notes)} files)")
    print(f"snapshot_html/ : {root / 'snapshot_html'} ({len(snaps)} files)")
    print(f"project jobs   : {pending_project_jobs}")
    print(f"README.md      : {'updated' if readme_changed else 'unchanged'}")


if __name__ == "__main__":
    main()
